### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7795

### ISSUE THREAD

**Issue by SizzleSnork** [raleighlittles/Snapchat-Chats-And-Location-Analyzer#1]
```
Traceback (most recent call last):
  File "C:\Snapchat-Chats-And-Location-Analyzer-main\snapchat_chat_parser.py", line 11, in <module>
    full_chat_history = json.load(json_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7795: character maps to <undefined>
```

**Comment by raleighlittles** [comment]
@SizzleSnork thanks for the issue, sorry that this problem is happening to you. Can you paste the json file you're using as input, into this tool: https://jsonlint.com/

to make sure the JSON is valid?

**Comment by SizzleSnork** [comment]
It says that the json is valid. I looked up the issue yesterday and someone said to add " 'encoding:' 'utf-8' ' " which prints json file when the program ran but theres only 4 results and the text is empty quotes.


"
    {
        "From": "angie_1",
        "Media Type": "MEDIA",
        "Created": "2022-06-13 19:37:49 UTC",
        "Text": "",
        "Created-Timestamp": 1655163469
    },
    {
        "From": "angie_1",
        "Media Type": "MEDIA",
        "Created": "2022-06-13 21:40:00 UTC",
        "Text": "",
        "Created-Timestamp": 1655170800
    },
    {
        "From": "angie_1",
        "Media Type": "MEDIA",
        "Created": "2022-06-19 22:21:54 UTC",
        "Text": "",
        "Created-Timestamp": 1655691714
    },
    {
        "To": "angie_1",
        "Media Type": "TEXT",
        "Created": "2022-06-19 22:37:38 UTC",
        "Text": 
"

**Comment by raleighlittles** [comment]
I think the problem is, that setting the encoding to UTF-8 doesn't work unless your file is actually encoded with UTF-8, which it sounds like is not the case here for some reason. If it is supposed to be UTF-8, then there's something wrong with the file.

Can you open the file in Notepad to see what the encoding is? https://stackoverflow.com/questions/3710374/get-encoding-of-a-file-in-windows

Also, if you have Notepad++ installed, would you mind sending me a few characters of the file, around where the errant character happens? 

https://superuser.com/questions/1277472/how-to-navigate-to-position-in-notepad

So go to say, 10 characters before, position 7795, and then copy about 10 characters after. If this includes some portion of a message you can just censor it.
@SizzleSnork

**Comment by SizzleSnork** [comment]
When i open it in notepad ++ the encoding is UTF-8

This is from characters 7,785 - 7,991
"😁"},{"From":"c2","Media Type":"TEXT","Created":"2023-03-25 15:46:12 UTC","Text":"And I said I already know her and you said no I don’t and you tried to act like a different person"}

Going through the json file with notepad ++, I can see the texts just in a different format until I get to char 164,992 which the json starts to say "'  ,"text":null}   "' for every piece of text until the end.
@raleighlittles

**Comment by SizzleSnork** [comment]
@raleighlittles I was able to fix it by adding encoding='utf8' at line 8:

 " with open("chat_history.json", encoding='utf8') as json_file: "
 
 Then at line 49, 
 
 "with open("{}_snapchat-chat-history-{}.json".format(timestamp, username), 'w', encoding='utf8') as output_json_file:"

**Comment by SizzleSnork** [comment]
Thank you for your help though!

**Comment by raleighlittles** [comment]
@SizzleSnork thanks for following up. I had assigned this issue to myself to look at, but I didn't quite have the time to actually investigate it on my own system.

I applied your fix to here: https://github.com/raleighlittles/Snapchat-Chats-And-Location-Analyzer/commit/59cda02e61900d687bf0fbd58bc8daadfdfce436
